@startuml
class EnemyFactory{
  void generate()
}

abstract class Enemy{
}

class Mummy{
}

class Ghost{
}

class ChunkModel{
}

ChunkModel .> EnemyFactory : uses
EnemyFactory ..> Enemy : creates
Enemy -|> Mummy
Ghost <|- Enemy
@enduml