@startuml
class Application{
  main()
}
class GameController{
  start()
  processAction()
}
class MapView{
  Screen
  ChunkView
  drawMap(MapModel)
}
class MapModel{
  chunks
  draw(PlayerModel)
}
Application -> GameController : uses
GameController -> MapView
GameController --> MapModel
@enduml